#!/bin/python3
"""
Sample Input 0

aabbbccde
Sample Output 0

b 3
a 2
c 2
"""


import math
import os
import random
import re
import sys



if __name__ == '__main__':
    s = input()
    char_dict={};
    for char in s:
        if char in char_dict:
            char_dict[char]=char_dict[char]+1
        else:
            char_dict[char]=1
    res1 = {key: val for key, val in sorted(char_dict.items(), key = lambda ele: ele[0])}
    res = {key: val for key, val in sorted(res1.items(), key = lambda ele: ele[1], reverse = True)}
    
    
out = dict(list(res.items())[0: 3])
for key, value in out.items():
   print(key, value)
